export const en = {
  requiredError: "This field is required",
  passwordError: "Minimum six characters for password",
  emailError: "Correct email format required",
  confirmPasswordError: "Your passwords do no match",
  goLoginPage: "Redirect to login page",
  goRegisterPage: "Redirect to register page",
  registerSuccess: "Register success",
  loginSuccess: "Login success",
  registerEmailError: "This email already exist",
  placeholderCoverImg: "Please enter your image link ...",
  addCoverButton: "Add Cover",
  editCoverButton: "Edit Cover",
  login: "Login",
  password: "Password",
  confirmPass: "Confirm Password",
  register: "Register",
  userName: "User Name",
  search: "Search",
  setting: "Setting",
  newPage: "New Page",
  notFoundEmail: "Not found email",
  somethingWrong: "Something went wrong !",
  deleteBlockSuccess: "Delete success",
  deleteBlock: "Delete item",
  submit: "Submit",
  remove: "Remove",
  maxFileSize: "The maximum size per file is 5MB",
  uploadFile: "Upload File",
  link: "Link",
  upload: "Upload",
  imgLinkInvalid: "Url not valid",
  deletePage: "Delete page",
  changeType: "Change item type",
  cantDelete: "Cant delete all block of page",
  addImg: "Add an image",
  myAcc: "My Account",
  mySetting: "My Setting",
  myProfile: "My Profile",
  accInfo: "Account Information",
  save: "Save",
  changeAva: "Change Avatar",
  theme: "Theme",
  lng: "Language",
  en: "En",
  vi: "Vi",
  pages: "Pages",
};
