export const en = {
  requiredError: "This field is required",
  passwordError: "Minimum six characters for password",
  emailError: "Correct email format required",
  confirmPasswordError: "Your passwords do no match",
  goLoginPage: "Redirect to login page",
  goRegisterPage: "Redirect to register page",
  registerSuccess: "Register success",
  loginSuccess: "Login success",
  registerEmailError: "This email already exist",
  placeholderCoverImg: "Please enter your image link ...",
  addCoverButton: "Add Cover",
  editCoverButton: "Edit Cover",
  login: "Login",
  password: "Password",
  confirmPass: "Confirm Password",
  register: "Register",
  userName: "User Name",
  search: "Search",
  setting: "Setting",
  newPage: "New Page",
  notFoundEmail: "Not found email",
  somethingWrong: "Something went wrong !",
  deleteBlockSuccess: "Delete success",
  deleteBlock: "Delete item",
  submit: "Submit",
  remove: "Remove",
  maxFileSize: "The maximum size per file is 5MB",
  uploadFile: "Upload File",
  link: "Link",
  upload: "Upload",
  imgLinkInvalid: "Url not valid",
  deletePage: "Delete page",
  changeType: "Change item type",
  cantDelete: "Cant delete all block of page",
  addImg: "Add an image",
  myAcc: "My Account",
  mySetting: "My Setting",
  myProfile: "My Profile",
  accInfo: "Account Information",
  save: "Save",
  changeAva: "Change Avatar",
  theme: "Theme",
  lng: "Language",
  en: "En",
  vi: "Vi",
  pages: "Pages",
  logout: "Logout",
  unauthorized: "Unauthorized",
  settingPermission: "Setting Permission",
  searchPlaceholder: "Type title of page to search",
  addSuccess: "Add Success",
  permissionPlaceholder: "Type username",
  pagesShare: "Share with me",
  editorHolder: "Type some note",
  homePageText: "Start note something for yourself",
  startNow: "Start Now",
  changePassword: "Change Password",
  changePasswordSuccess: "Change Password Success",
  newPassword: "New Password",
  confirmNewPass: "Confirm New Password",
  comment: "Comment",
  commentOf: "Comment of",
  commentHolder: "Enter your comment",
  userListing: "User Listing",
  pageListing: "Page Listing",
  searchUser: "Enter user name or email",
  noData: "Not found data",
  noDataDecs: " Please check for any missing or incorrect parameters",
  edit: "Edit",
  delete: "Delete",
  editUser: "Edit User",
  addUser: "Add User",
  deleteUser: "Delete User",
  deleteUserDecs: "Are you sure you want to delete this user ?",
  deletePageDecs: "Are you sure you want to delete this page ?",
  cancel: "Cancel",
  deletePageError: "Author of this page only have 1 page left !",
  addPage: "Add Page",
  view: "View",
  title: "Title",
  author: "Author",
  searchPage: "Enter title of page",
  success: "Success",
  month_1: "Jan",
  month_2: "Feb",
  month_3: "Mar",
  month_4: "Apr",
  month_5: "May",
  month_6: "Jun",
  month_7: "Jul",
  month_8: "Aug",
  month_9: "Sep",
  month_10: "Oct",
  month_11: "Nov",
  month_12: "Dec",
  chartUser: "User statistics",
  chartUserTitle: "Chart user in ",
  chartUserEle: "New User",
  chartPage: "Page statistics",
  chartPageTitle: "Chart page in ",
  chartPageEle: "New Page",
  blockErrorMessage:
    "Accounts that have been blocked cannot perform this action",
  blockUser: "Block User",
  unblockUser: "Unblock User",
  blockUserDesc: "Are you sure you want to block this user ?",
  unblockUserDesc: "Are you sure you want to unblock this user ?",
  nonPremiumError: "Please upgrade your account to process this action",
  premiumTitle: "Upgrade your account",
  premiumBenefitDesc: "Premium account can have :",
  premiumBenefit_1: "Unlimited page",
  premiumBenefit_2: "Unlimited block in page",
  premiumBenefit_3: "Unlimited user share for page",
  premiumBtn: "Upgrade now",
  premiumText: "Premium",
  add: "Add",
  removeSuccess: "Remove Successful",
  lastUpdate: "Last update",
  general: "General",
  permissionGeneral: "General Permission",
  any: "Everyone",
  limit: "Restrict",
  permissionAnyDesc: "Anyone with the link can access this note",
  permissionLimitDesc: "Only authorized people can access this note",
  copyLink: "Copy Link",
};
