export const vi = {
  requiredError: "Trường này là bắt buộc",
  passwordError: "Mật khẩu cần tối thiểu 6 ký tự",
  emailError: "Hãy nhập email đúng cú pháp",
  confirmPasswordError: "Mật khẩu không khớp",
  goLoginPage: "Tới trang đăng nhập",
  goRegisterPage: "Tới trnag đăng ký",
  registerSuccess: "Đăng ký thành công",
  loginSuccess: "Đăng nhập thành công",
  registerEmailError: "Email này đã tồn tại",
  placeholderCoverImg: "Nhập đường dẫn ảnh ...",
  addCoverButton: "Thêm ảnh nền",
  editCoverButton: "Sửa ảnh nền",
  login: "Đăng nhập",
  password: "Mật khẩu",
  confirmPass: "Nhập lại mật khẩu",
  register: "Đăng ký",
  userName: "Tên người dùng",
  search: "Tìm kiếm",
  setting: "Cài đặt",
  newPage: "Tạo trang mới",
  notFoundEmail: "Không tìm thấy email",
  somethingWrong: "Có sự cố sảy ra !",
  deleteBlockSuccess: "Xoá thành công",
  deleteBlock: "Xoá",
  submit: "Gửi",
  remove: "Gỡ bỏ",
  maxFileSize: "Dung lượng tối đa là 5MB",
  uploadFile: "Tải lên",
  link: "Link",
  upload: "Tải lên",
  imgLinkInvalid: "Đường đẫn không hợp lệ",
  deletePage: "Xoá trang",
  changeType: "Đổi kiểu",
  cantDelete: "Không thể xoá toàn bộ dữ liệu",
  addImg: "Thêm ảnh",
  myAcc: "Tài khoản",
  mySetting: "Cài đặt",
  myProfile: "Cá nhân",
  accInfo: "Thông tin tài khoản",
  save: "Lưu",
  changeAva: "Đổi Avatar",
  theme: "Màu nền",
  lng: "Ngôn ngữ",
  en: "En",
  vi: "Vi",
  pages: "Trang nhớ",
  logout: "Đăng xuất",
  settingPermission: "Quản lý chia sẻ",
  searchPlaceholder: "Nhập tiêu đề trang nhớ",
  permissionPlaceholder: "Nhập tên người dùng",
};
